# Generated by Django 4.2.5 on 2023-09-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('situacao', models.BooleanField(verbose_name='Situação da chave')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraEmprestimo', models.DateTimeField(verbose_name='Hora Emprestimo')),
                ('dataHoraDevolucao', models.DateTimeField(verbose_name='Hora Devolução')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('contato', models.CharField(max_length=15, verbose_name='Contato do servidor')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
        ),
    ]
