# Generated by Django 4.2.5 on 2023-09-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='status',
        ),
    ]
