# Generated by Django 4.2.5 on 2023-09-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chave_status_alter_emprestimo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='chave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.chave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chave',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Situação da chave'),
        ),
    ]
