# Generated by Django 4.2.5 on 2023-09-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emprestimo_chave_alter_chave_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='chave',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='chaveEmprestada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chaveEmprestimo', to='core.chave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='servidorDevolucao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servidorDevolucao', to='core.servidor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='servidorEmprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servidorEmprestimo', to='core.servidor'),
            preserve_default=False,
        ),
    ]
