# Generated by Django 4.2.5 on 2023-09-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_emprestimo_chave_emprestimo_chaveemprestada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='servidorDevolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servidorDevolucao', to='core.servidor'),
        ),
    ]
