# Generated by Django 4.2.5 on 2023-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emprestimo_servidordevolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataHoraDevolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Devolução'),
        ),
    ]
